# coding: utf-8

"""
    SecureFonts

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from org.wso2.client.api.SecureFonts.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = org.wso2.client.api.SecureFonts.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_glyphs_encodetext_post(self):
        """Test case for glyphs_encodetext_post

        """
        pass

    def test_glyphs_getfont_fontname_name_get(self):
        """Test case for glyphs_getfont_fontname_name_get

        """
        pass

    def test_glyphs_myfontprefixes_all_get(self):
        """Test case for glyphs_myfontprefixes_all_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
