# coding: utf-8

"""
    ShiftText

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@securelyshare.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.org.wso2.client.model.ShiftText.api_error import ApiError  # noqa: E501
from openapi_client.rest import ApiException

class TestApiError(unittest.TestCase):
    """ApiError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.api_error.ApiError()  # noqa: E501
        if include_optional :
            return ApiError(
                attribute_name = 'Encoder process', 
                code = 5005, 
                debug_message = 'Something went wrong at line 177', 
                http_status = '400', 
                message = 'Check your payload', 
                status = 404, 
                sub_errors = [
                    openapi_client.models.api_sub_error.API Sub Error(
                        message = 'data in too long', )
                    ], 
                timestamp = 912345612344
            )
        else :
            return ApiError(
        )

    def testApiError(self):
        """Test ApiError"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
