# coding: utf-8

"""
    ShiftText

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@securelyshare.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from org.wso2.client.api.ShiftText.encoder_service_api import EncoderServiceApi  # noqa: E501
from openapi_client.rest import ApiException


class TestEncoderServiceApi(unittest.TestCase):
    """EncoderServiceApi unit test stubs"""

    def setUp(self):
        self.api = org.wso2.client.api.ShiftText.encoder_service_api.EncoderServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fonts_encodetext_post(self):
        """Test case for fonts_encodetext_post

        API endpoint to encode content  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
