# coding: utf-8

"""
    ShiftText

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@securelyshare.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.org.wso2.client.model.ShiftText.scope import Scope  # noqa: E501
from openapi_client.rest import ApiException

class TestScope(unittest.TestCase):
    """Scope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Scope
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.scope.Scope()  # noqa: E501
        if include_optional :
            return Scope(
                name = 'SESSION', 
                value = '6QfmF0rWLiPcbu57g785FX6ZlOca'
            )
        else :
            return Scope(
                name = 'SESSION',
                value = '6QfmF0rWLiPcbu57g785FX6ZlOca',
        )

    def testScope(self):
        """Test Scope"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
